#!/bin/bash

set -x

rm index.*

wget  http://facebook.com
wget  http://google.com
wget  http://amazon.com
wget  http://youtube.com
wget  http://yelp.com
wget  http://wikipedia.com
wget  http://yahoo.com
wget  http://instagram.com
wget  http://fandom.com
wget  http://buzzfeed.com
wget  http://linkedin.com
wget  http://ebay.com
wget  http://espn.com
wget  http://medicalnewstoday.com
wget  http://urbandictionary.com
wget  http://msn.com
wget  http://netflix.com
wget  http://live.com
wget  http://giphy.com
wget  http://walmart.com
wget  http://imgur.com
wget  http://whitepages.com
wget  http://thehill.com
wget  http://www.legacy.com
wget  http://bustle.com
wget  http://microsoft.com
wget  http://stackexchange.com
wget  http://glassdoor.com
wget  http://ranker.com
wget  http://pinterest.com
wget  http://zillow.com
wget  http://people.com
wget  http://indeed.com
wget  http://bing.com
wget  http://worldlifestyle.com
wget  http://twentytwowords.com
wget  http://cheatsheet.com
wget  http://wellsfargo.com
wget  http://refinery29.com
wget  http://buzzfeednews.com
wget  http://science101.com
wget  http://gfycat.com
wget  http://drudgereport.com
wget  http://goodreads.com
wget  http://twitter.com
wget  http://quizlet.com
wget  http://slate.com
wget  http://littlethings.com
wget  http://washingtonexaminer.com
wget  http://apple.com
wget  http://metropcs.mobi
wget  http://coolimba.com
wget  http://univision.com
wget  http://nickiswift.com
wget  http://politico.com
wget  http://cnbc.com
wget  http://icepop.com
wget  http://hulu.com
wget  http://answers.com
wget  http://thekitchn.com
wget  http://bobshideout.com
wget  http://cafemom.com
wget  http://weather.com
wget  http://theverge.com
wget  http://comicbook.com
wget  http://radio.com
wget  http://thoughtcatalog.com
wget  http://mercurynews.com
wget  http://graduatez.com
wget  http://wattpad.com
wget  http://groupon.com
wget  http://businessinsider.com
wget  http://eonline.com
wget  http://healthgrades.com
wget  http://rollingstone.com
wget  http://mentalfloss.com
wget  http://mlb.com
wget  http://dailycaller.com
wget  http://uproxx.com
wget  http://vox.com
wget  http://radaronline.com
wget  http://polygon.com
wget  http://variety.com
wget  http://history101.com
wget  http://magiquiz.com
wget  http://247sports.com
wget  http://newyorker.com
wget  http://gamespot.com
wget  http://stackoverflow.com
wget  http://sixflags.com
wget  http://snopes.com
wget  http://booking.com
wget  http://thechive.com
wget  http://popculture.com
wget  http://flightaware.com
wget  http://howtogeek.com
wget  http://imore.com
wget  http://finance101.com
wget  http://dailymotion.com
wget  http://directexpose.com
wget  http://spanishdict.com
wget  http://hometalk.com
wget  http://facty.com
wget  http://city-data.com
wget  http://vitals.com
wget  http://thekrazycouponlady.com
wget  http://wired.com
wget  http://washingtontimes.com
wget  http://topixstars.com
wget  http://medicinenet.com
wget  http://shareasale-analytics.com
wget  http://thepennyhoarder.com
wget  http://rxlist.com
wget  http://tiebreaker.com
wget  http://androidcentral.com
wget  http://songkick.com
wget  http://startribune.com
wget  http://edmunds.com
wget  http://offers.com
wget  http://buff.ly
wget  http://axs.com
wget  http://yourtango.com
wget  http://mozilla.org
wget  http://bonappetit.com
wget  http://simbaly.com
wget  http://github.com
wget  http://lifedaily.com
wget  http://carfax.com
wget  http://dailydot.com
wget  http://chasethetrend.com
wget  http://knowyourmeme.com
wget  http://aol.com
wget  http://findagrave.com
wget  http://rawstory.com
wget  http://tasty.co
wget  http://cars.com
wget  http://denverpost.com
wget  http://gardeningknowhow.com
wget  http://hp.com
wget  http://looper.com
wget  http://doordash.com
wget  http://vanityfair.com
wget  http://redfin.com
wget  http://westernjournal.com
wget  http://slideshare.net
wget  http://sciencealert.com
wget  http://inverse.com
wget  http://epicurious.com
wget  http://overstock.com
wget  http://drugs.com
wget  http://cracked.com
wget  http://ajc.com
wget  http://paypal.com
wget  http://parentztalk.com
wget  http://kayak.com
wget  http://expedia.com
wget  http://hotels.com
wget  http://adp.com
wget  http://romper.com
wget  http://bizrate.com
wget  http://livestly.com
wget  http://brainly.com
wget  http://baseball-reference.com
wget  http://force.com
wget  http://patreon.com
wget  http://consumerreports.org
wget  http://newarena.com
wget  http://harborfreight.com
wget  http://sprint.com
wget  http://thelist.com
wget  http://nextdoor.com
wget  http://dailykos.com
wget  http://duckduckgo.com
wget  http://cox.net
wget  http://theepochtimes.com
wget  http://collider.com
wget  http://southwest.com
wget  http://food52.com
wget  http://lifewire.com
wget  http://glamour.com
wget  http://marriott.com
wget  http://pgatour.com
wget  http://state.gov
wget  http://firefox.com
wget  http://craigslist.org
wget  http://united.com
wget  http://mapquest.com
wget  http://beenverified.com
wget  http://macrumors.com
wget  http://eater.com
wget  http://sendgrid.net
wget  http://discord.gg
wget  http://thegatewaypundit.com
wget  http://clicktripz.com
wget  http://adobe.com
wget  http://apartments.com
wget  http://nesn.com
wget  http://wsbtv.com
wget  http://draxe.com
wget  http://gunbroker.com
wget  http://self.com
wget  http://verizon.com
wget  http://miamiherald.com
wget  http://trend-chaser.com
wget  http://foxbusiness.com
wget  http://timeanddate.com
wget  http://okta.com
wget  http://campingworld.com
wget  http://docusign.net
wget  http://tripadvisor.com
wget  http://msnbc.com
wget  http://aliexpress.com
wget  http://alltrails.com
wget  http://apartmenttherapy.com
wget  http://horoscope.com
wget  http://vogue.com
wget  http://ziprecruiter.com
wget  http://hilton.com
wget  http://nps.gov
wget  http://seeitlive.co
wget  http://gq.com
wget  http://sfgate.com
wget  http://factinate.com
wget  http://trivago.com
wget  http://itstillruns.com
wget  http://patheos.com
wget  http://atlasobscura.com
wget  http://basketball-reference.com
wget  http://vrbo.com
wget  http://harvard.edu
wget  http://archive.org
wget  http://belk.com
wget  http://superuser.com
wget  http://syf.com
wget  http://mydailymagazine.com
wget  http://americascardroom.eu
wget  http://catchpoint.com
wget  http://rare.us
wget  http://patch.com
wget  http://golfdigest.com
wget  http://medallia.com
wget  http://definition.org
wget  http://sbnation.com
wget  http://dropbox.com
wget  http://nbcsports.com
wget  http://sears.com
wget  http://flickr.com
wget  http://wikipedia.org
wget  http://avvo.com
wget  http://spectrum.net
wget  http://advanceautoparts.com
wget  http://zimbio.com
wget  http://clickondetroit.com
wget  http://progressive.com
wget  http://aarp.org
wget  http://kiwireport.com
wget  http://justanswer.com
wget  http://mylife.com
wget  http://worldation.com
wget  http://apnews.com
wget  http://outsideonline.com
wget  http://redd.it
wget  http://dell.com
wget  http://windowscentral.com
wget  http://cvs.com
wget  http://cruisecritic.com
wget  http://topixoffbeat.com
wget  http://tributes.com
wget  http://nation.com
wget  http://homeadvisor.com
wget  http://wish.com
wget  http://uscis.gov
wget  http://abcactionnews.com
wget  http://usaa.com
wget  http://cdc.gov
wget  http://eventbrite.com
wget  http://tractorsupply.com
wget  http://phys.org
wget  http://mnn.com
wget  http://tmz.com
wget  http://thegrio.com
wget  http://astrology.com
wget  http://local10.com
wget  http://searchencrypt.com
wget  http://tracfone.com
wget  http://click2houston.com
wget  http://fidelity.com
wget  http://spectrum.com
wget  http://sharepoint.com
wget  http://amzn.to
wget  http://lyft.com
wget  http://almanac.com
wget  http://bbt.com
wget  http://azlyrics.com
wget  http://pitchfork.com
wget  http://myjobhelper.com
wget  http://joinhoney.com
wget  http://shopify.com
wget  http://mega.nz
wget  http://reservations.com
wget  http://truthfinder.com
wget  http://onelink.me
wget  http://autotrader.com
wget  http://pcgamer.com
wget  http://sportzbonanza.com
wget  http://tacobell.com
wget  http://squareup.com
wget  http://lonelyplanet.com
wget  http://abc15.com
wget  http://nasdaq.com
wget  http://travelocity.com
wget  http://clutchpoints.com
wget  http://ubi.com
wget  http://landsend.com
wget  http://homehacks.co
wget  http://ca.gov
wget  http://kroger.com
wget  http://bodybuilding.com
wget  http://falafelandcaviar.com
wget  http://topixrewind.com
wget  http://amctheatres.com
wget  http://curbed.com
wget  http://mom.me
wget  http://itstillworks.com
wget  http://siriusxm.com
wget  http://king.com
wget  http://pbs.org
wget  http://fixya.com
wget  http://zerohedge.com
wget  http://topixparenthood.com
wget  http://liveleak.com
wget  http://psychologytoday.com
wget  http://theprimarymarket.com
wget  http://nationalinterest.org
wget  http://godaddy.com
wget  http://custhelp.com
wget  http://hollywoodreporter.com
wget  http://cntraveler.com
wget  http://zappos.com
wget  http://starbucks.com
wget  http://teenvogue.com
wget  http://trueactivist.com
wget  http://frontgatetickets.com
wget  http://news4jax.com
wget  http://wxyz.com
wget  http://myshopify.com
wget  http://google.org
wget  http://popsugar.com
wget  http://indiewire.com
wget  http://wideopeneats.com
wget  http://bestdeals.today
wget  http://thezoereport.com
wget  http://zoom.us
wget  http://poshmark.com
wget  http://good.is
wget  http://getpocket.com
wget  http://statefarm.com
wget  http://partypoker.com
wget  http://rakuten.com
wget  http://cbssports.com
wget  http://makeuseof.com
wget  http://kickstarter.com
wget  http://nba.com
wget  http://wideopencountry.com
wget  http://staples.com
wget  http://eventful.com
wget  http://grubhub.com
wget  http://ny.gov
wget  http://pch.com
wget  http://zmenu.com
wget  http://orbitz.com
wget  http://53.com
wget  http://daily-stuff.com
wget  http://va.gov
wget  http://researchgate.net
wget  http://whatsapp.com
wget  http://silverscreenandroll.com
wget  http://arstechnica.com
wget  http://wordplays.com
wget  http://alternativenation.net
wget  http://americanexpress.com
wget  http://sacbee.com
wget  http://alibaba.com
wget  http://emedicinehealth.com
wget  http://instructables.com
wget  http://gearpatrol.com
wget  http://ebaumsworld.com
wget  http://healthversed.com
wget  http://windows.net

# bad ssl
wget  http://expired.badssl.com
wget  http://wrong.host.badssl.com
wget  http://self-signed.badssl.com
wget  http://untrusted-root.badssl.com
wget  http://superfish.badssl.com
wget  http://edellroot.badssl.com
wget  http://dsdtestprovider.badssl.com
wget  http://preact-cli.badssl.com
wget  http://webpack-dev-server.badssl.com
wget  http://sha1-intermediate.badssl.com
wget  http://rc4.badssl.com
wget  http://rc4-md5.badssl.com
wget  http://dh480.badssl.com
wget  http://dh512.badssl.com
wget  http://dh1024.badssl.com
wget  http://null.badssl.com
wget  http://tls-v1-0.badssl.com
wget  http://tls-v1-1.badssl.com
wget  http://cbc.badssl.com
wget  http://3des.badssl.com
wget  http://revoked.badssl.com
wget  http://pinning-test.badssl.com
wget  http://invalid-expected-sct.badssl.com
wget  http://10000-sans.badssl.com
wget  http://sha384.badssl.com
wget  http://sha512.badssl.com
wget  http://rsa8192.badssl.com
wget  http://no-subject.badssl.com
wget  http://no-common-name.badssl.com
wget  http://incomplete-chain.badssl.com
wget  http://tls-v1-2.badssl.com
wget  http://sha256.badssl.com
wget  http://rsa2048.badssl.com
wget  http://ecc256.badssl.com
wget  http://ecc384.badssl.com
wget  http://extended-validation.badssl.com
wget  http://mozilla-modern.badssl.com

rm index.*
