#!/bin/bash

set -x

rm index.*

wget --no-check-certificate https://facebook.com
wget --no-check-certificate https://google.com
wget --no-check-certificate https://amazon.com
wget --no-check-certificate https://youtube.com
wget --no-check-certificate https://yelp.com
wget --no-check-certificate https://wikipedia.com
wget --no-check-certificate https://yahoo.com
wget --no-check-certificate https://instagram.com
wget --no-check-certificate https://fandom.com
wget --no-check-certificate https://buzzfeed.com
wget --no-check-certificate https://linkedin.com
wget --no-check-certificate https://ebay.com
wget --no-check-certificate https://espn.com
wget --no-check-certificate https://medicalnewstoday.com
wget --no-check-certificate https://urbandictionary.com
wget --no-check-certificate https://msn.com
wget --no-check-certificate https://netflix.com
wget --no-check-certificate https://live.com
wget --no-check-certificate https://giphy.com
wget --no-check-certificate https://walmart.com
wget --no-check-certificate https://imgur.com
wget --no-check-certificate https://whitepages.com
wget --no-check-certificate https://thehill.com
wget --no-check-certificate https://www.legacy.com
wget --no-check-certificate https://bustle.com
wget --no-check-certificate https://microsoft.com
wget --no-check-certificate https://stackexchange.com
wget --no-check-certificate https://glassdoor.com
wget --no-check-certificate https://ranker.com
wget --no-check-certificate https://pinterest.com
wget --no-check-certificate https://zillow.com
wget --no-check-certificate https://people.com
wget --no-check-certificate https://indeed.com
wget --no-check-certificate https://bing.com
wget --no-check-certificate https://worldlifestyle.com
wget --no-check-certificate https://twentytwowords.com
wget --no-check-certificate https://cheatsheet.com
wget --no-check-certificate https://wellsfargo.com
wget --no-check-certificate https://refinery29.com
wget --no-check-certificate https://buzzfeednews.com
wget --no-check-certificate https://science101.com
wget --no-check-certificate https://gfycat.com
wget --no-check-certificate https://drudgereport.com
wget --no-check-certificate https://goodreads.com
wget --no-check-certificate https://twitter.com
wget --no-check-certificate https://quizlet.com
wget --no-check-certificate https://slate.com
wget --no-check-certificate https://littlethings.com
wget --no-check-certificate https://washingtonexaminer.com
wget --no-check-certificate https://apple.com
wget --no-check-certificate https://metropcs.mobi
wget --no-check-certificate https://coolimba.com
wget --no-check-certificate https://univision.com
wget --no-check-certificate https://nickiswift.com
wget --no-check-certificate https://politico.com
wget --no-check-certificate https://cnbc.com
wget --no-check-certificate https://icepop.com
wget --no-check-certificate https://hulu.com
wget --no-check-certificate https://answers.com
wget --no-check-certificate https://thekitchn.com
wget --no-check-certificate https://bobshideout.com
wget --no-check-certificate https://cafemom.com
wget --no-check-certificate https://weather.com
wget --no-check-certificate https://theverge.com
wget --no-check-certificate https://comicbook.com
wget --no-check-certificate https://radio.com
wget --no-check-certificate https://thoughtcatalog.com
wget --no-check-certificate https://mercurynews.com
wget --no-check-certificate https://graduatez.com
wget --no-check-certificate https://wattpad.com
wget --no-check-certificate https://groupon.com
wget --no-check-certificate https://businessinsider.com
wget --no-check-certificate https://eonline.com
wget --no-check-certificate https://healthgrades.com
wget --no-check-certificate https://rollingstone.com
wget --no-check-certificate https://mentalfloss.com
wget --no-check-certificate https://mlb.com
wget --no-check-certificate https://dailycaller.com
wget --no-check-certificate https://uproxx.com
wget --no-check-certificate https://vox.com
wget --no-check-certificate https://radaronline.com
wget --no-check-certificate https://polygon.com
wget --no-check-certificate https://variety.com
wget --no-check-certificate https://history101.com
wget --no-check-certificate https://magiquiz.com
wget --no-check-certificate https://247sports.com
wget --no-check-certificate https://newyorker.com
wget --no-check-certificate https://gamespot.com
wget --no-check-certificate https://stackoverflow.com
wget --no-check-certificate https://sixflags.com
wget --no-check-certificate https://snopes.com
wget --no-check-certificate https://booking.com
wget --no-check-certificate https://thechive.com
wget --no-check-certificate https://popculture.com
wget --no-check-certificate https://flightaware.com
wget --no-check-certificate https://howtogeek.com
wget --no-check-certificate https://imore.com
wget --no-check-certificate https://finance101.com
wget --no-check-certificate https://dailymotion.com
wget --no-check-certificate https://directexpose.com
wget --no-check-certificate https://spanishdict.com
wget --no-check-certificate https://hometalk.com
wget --no-check-certificate https://facty.com
wget --no-check-certificate https://city-data.com
wget --no-check-certificate https://vitals.com
wget --no-check-certificate https://thekrazycouponlady.com
wget --no-check-certificate https://wired.com
wget --no-check-certificate https://washingtontimes.com
wget --no-check-certificate https://topixstars.com
wget --no-check-certificate https://medicinenet.com
wget --no-check-certificate https://shareasale-analytics.com
wget --no-check-certificate https://thepennyhoarder.com
wget --no-check-certificate https://rxlist.com
wget --no-check-certificate https://tiebreaker.com
wget --no-check-certificate https://androidcentral.com
wget --no-check-certificate https://songkick.com
wget --no-check-certificate https://startribune.com
wget --no-check-certificate https://edmunds.com
wget --no-check-certificate https://offers.com
wget --no-check-certificate https://buff.ly
wget --no-check-certificate https://axs.com
wget --no-check-certificate https://yourtango.com
wget --no-check-certificate https://mozilla.org
wget --no-check-certificate https://bonappetit.com
wget --no-check-certificate https://simbaly.com
wget --no-check-certificate https://github.com
wget --no-check-certificate https://lifedaily.com
wget --no-check-certificate https://carfax.com
wget --no-check-certificate https://dailydot.com
wget --no-check-certificate https://chasethetrend.com
wget --no-check-certificate https://knowyourmeme.com
wget --no-check-certificate https://aol.com
wget --no-check-certificate https://findagrave.com
wget --no-check-certificate https://rawstory.com
wget --no-check-certificate https://tasty.co
wget --no-check-certificate https://cars.com
wget --no-check-certificate https://denverpost.com
wget --no-check-certificate https://gardeningknowhow.com
wget --no-check-certificate https://hp.com
wget --no-check-certificate https://looper.com
wget --no-check-certificate https://doordash.com
wget --no-check-certificate https://vanityfair.com
wget --no-check-certificate https://redfin.com
wget --no-check-certificate https://westernjournal.com
wget --no-check-certificate https://slideshare.net
wget --no-check-certificate https://sciencealert.com
wget --no-check-certificate https://inverse.com
wget --no-check-certificate https://epicurious.com
wget --no-check-certificate https://overstock.com
wget --no-check-certificate https://drugs.com
wget --no-check-certificate https://cracked.com
wget --no-check-certificate https://ajc.com
wget --no-check-certificate https://paypal.com
wget --no-check-certificate https://parentztalk.com
wget --no-check-certificate https://kayak.com
wget --no-check-certificate https://expedia.com
wget --no-check-certificate https://hotels.com
wget --no-check-certificate https://adp.com
wget --no-check-certificate https://romper.com
wget --no-check-certificate https://bizrate.com
wget --no-check-certificate https://livestly.com
wget --no-check-certificate https://brainly.com
wget --no-check-certificate https://baseball-reference.com
wget --no-check-certificate https://force.com
wget --no-check-certificate https://patreon.com
wget --no-check-certificate https://consumerreports.org
wget --no-check-certificate https://newarena.com
wget --no-check-certificate https://harborfreight.com
wget --no-check-certificate https://sprint.com
wget --no-check-certificate https://thelist.com
wget --no-check-certificate https://nextdoor.com
wget --no-check-certificate https://dailykos.com
wget --no-check-certificate https://duckduckgo.com
wget --no-check-certificate https://cox.net
wget --no-check-certificate https://theepochtimes.com
wget --no-check-certificate https://collider.com
wget --no-check-certificate https://southwest.com
wget --no-check-certificate https://food52.com
wget --no-check-certificate https://lifewire.com
wget --no-check-certificate https://glamour.com
wget --no-check-certificate https://marriott.com
wget --no-check-certificate https://pgatour.com
wget --no-check-certificate https://state.gov
wget --no-check-certificate https://firefox.com
wget --no-check-certificate https://craigslist.org
wget --no-check-certificate https://united.com
wget --no-check-certificate https://mapquest.com
wget --no-check-certificate https://beenverified.com
wget --no-check-certificate https://macrumors.com
wget --no-check-certificate https://eater.com
wget --no-check-certificate https://sendgrid.net
wget --no-check-certificate https://discord.gg
wget --no-check-certificate https://thegatewaypundit.com
wget --no-check-certificate https://clicktripz.com
wget --no-check-certificate https://adobe.com
wget --no-check-certificate https://apartments.com
wget --no-check-certificate https://nesn.com
wget --no-check-certificate https://wsbtv.com
wget --no-check-certificate https://draxe.com
wget --no-check-certificate https://gunbroker.com
wget --no-check-certificate https://self.com
wget --no-check-certificate https://verizon.com
wget --no-check-certificate https://miamiherald.com
wget --no-check-certificate https://trend-chaser.com
wget --no-check-certificate https://foxbusiness.com
wget --no-check-certificate https://timeanddate.com
wget --no-check-certificate https://okta.com
wget --no-check-certificate https://campingworld.com
wget --no-check-certificate https://docusign.net
wget --no-check-certificate https://tripadvisor.com
wget --no-check-certificate https://msnbc.com
wget --no-check-certificate https://aliexpress.com
wget --no-check-certificate https://alltrails.com
wget --no-check-certificate https://apartmenttherapy.com
wget --no-check-certificate https://horoscope.com
wget --no-check-certificate https://vogue.com
wget --no-check-certificate https://ziprecruiter.com
wget --no-check-certificate https://hilton.com
wget --no-check-certificate https://nps.gov
wget --no-check-certificate https://seeitlive.co
wget --no-check-certificate https://gq.com
wget --no-check-certificate https://sfgate.com
wget --no-check-certificate https://factinate.com
wget --no-check-certificate https://trivago.com
wget --no-check-certificate https://itstillruns.com
wget --no-check-certificate https://patheos.com
wget --no-check-certificate https://atlasobscura.com
wget --no-check-certificate https://basketball-reference.com
wget --no-check-certificate https://vrbo.com
wget --no-check-certificate https://harvard.edu
wget --no-check-certificate https://archive.org
wget --no-check-certificate https://belk.com
wget --no-check-certificate https://superuser.com
wget --no-check-certificate https://syf.com
wget --no-check-certificate https://mydailymagazine.com
wget --no-check-certificate https://americascardroom.eu
wget --no-check-certificate https://catchpoint.com
wget --no-check-certificate https://rare.us
wget --no-check-certificate https://patch.com
wget --no-check-certificate https://golfdigest.com
wget --no-check-certificate https://medallia.com
wget --no-check-certificate https://definition.org
wget --no-check-certificate https://sbnation.com
wget --no-check-certificate https://dropbox.com
wget --no-check-certificate https://nbcsports.com
wget --no-check-certificate https://sears.com
wget --no-check-certificate https://flickr.com
wget --no-check-certificate https://wikipedia.org
wget --no-check-certificate https://avvo.com
wget --no-check-certificate https://spectrum.net
wget --no-check-certificate https://advanceautoparts.com
wget --no-check-certificate https://zimbio.com
wget --no-check-certificate https://clickondetroit.com
wget --no-check-certificate https://progressive.com
wget --no-check-certificate https://aarp.org
wget --no-check-certificate https://kiwireport.com
wget --no-check-certificate https://justanswer.com
wget --no-check-certificate https://mylife.com
wget --no-check-certificate https://worldation.com
wget --no-check-certificate https://apnews.com
wget --no-check-certificate https://outsideonline.com
wget --no-check-certificate https://redd.it
wget --no-check-certificate https://dell.com
wget --no-check-certificate https://windowscentral.com
wget --no-check-certificate https://cvs.com
wget --no-check-certificate https://cruisecritic.com
wget --no-check-certificate https://topixoffbeat.com
wget --no-check-certificate https://tributes.com
wget --no-check-certificate https://nation.com
wget --no-check-certificate https://homeadvisor.com
wget --no-check-certificate https://wish.com
wget --no-check-certificate https://uscis.gov
wget --no-check-certificate https://abcactionnews.com
wget --no-check-certificate https://usaa.com
wget --no-check-certificate https://cdc.gov
wget --no-check-certificate https://eventbrite.com
wget --no-check-certificate https://tractorsupply.com
wget --no-check-certificate https://phys.org
wget --no-check-certificate https://mnn.com
wget --no-check-certificate https://tmz.com
wget --no-check-certificate https://thegrio.com
wget --no-check-certificate https://astrology.com
wget --no-check-certificate https://local10.com
wget --no-check-certificate https://searchencrypt.com
wget --no-check-certificate https://tracfone.com
wget --no-check-certificate https://click2houston.com
wget --no-check-certificate https://fidelity.com
wget --no-check-certificate https://spectrum.com
wget --no-check-certificate https://sharepoint.com
wget --no-check-certificate https://amzn.to
wget --no-check-certificate https://lyft.com
wget --no-check-certificate https://almanac.com
wget --no-check-certificate https://bbt.com
wget --no-check-certificate https://azlyrics.com
wget --no-check-certificate https://pitchfork.com
wget --no-check-certificate https://myjobhelper.com
wget --no-check-certificate https://joinhoney.com
wget --no-check-certificate https://shopify.com
wget --no-check-certificate https://mega.nz
wget --no-check-certificate https://reservations.com
wget --no-check-certificate https://truthfinder.com
wget --no-check-certificate https://onelink.me
wget --no-check-certificate https://autotrader.com
wget --no-check-certificate https://pcgamer.com
wget --no-check-certificate https://sportzbonanza.com
wget --no-check-certificate https://tacobell.com
wget --no-check-certificate https://squareup.com
wget --no-check-certificate https://lonelyplanet.com
wget --no-check-certificate https://abc15.com
wget --no-check-certificate https://nasdaq.com
wget --no-check-certificate https://travelocity.com
wget --no-check-certificate https://clutchpoints.com
wget --no-check-certificate https://ubi.com
wget --no-check-certificate https://landsend.com
wget --no-check-certificate https://homehacks.co
wget --no-check-certificate https://ca.gov
wget --no-check-certificate https://kroger.com
wget --no-check-certificate https://bodybuilding.com
wget --no-check-certificate https://falafelandcaviar.com
wget --no-check-certificate https://topixrewind.com
wget --no-check-certificate https://amctheatres.com
wget --no-check-certificate https://curbed.com
wget --no-check-certificate https://mom.me
wget --no-check-certificate https://itstillworks.com
wget --no-check-certificate https://siriusxm.com
wget --no-check-certificate https://king.com
wget --no-check-certificate https://pbs.org
wget --no-check-certificate https://fixya.com
wget --no-check-certificate https://zerohedge.com
wget --no-check-certificate https://topixparenthood.com
wget --no-check-certificate https://liveleak.com
wget --no-check-certificate https://psychologytoday.com
wget --no-check-certificate https://theprimarymarket.com
wget --no-check-certificate https://nationalinterest.org
wget --no-check-certificate https://godaddy.com
wget --no-check-certificate https://custhelp.com
wget --no-check-certificate https://hollywoodreporter.com
wget --no-check-certificate https://cntraveler.com
wget --no-check-certificate https://zappos.com
wget --no-check-certificate https://starbucks.com
wget --no-check-certificate https://teenvogue.com
wget --no-check-certificate https://trueactivist.com
wget --no-check-certificate https://frontgatetickets.com
wget --no-check-certificate https://news4jax.com
wget --no-check-certificate https://wxyz.com
wget --no-check-certificate https://myshopify.com
wget --no-check-certificate https://google.org
wget --no-check-certificate https://popsugar.com
wget --no-check-certificate https://indiewire.com
wget --no-check-certificate https://wideopeneats.com
wget --no-check-certificate https://bestdeals.today
wget --no-check-certificate https://thezoereport.com
wget --no-check-certificate https://zoom.us
wget --no-check-certificate https://poshmark.com
wget --no-check-certificate https://good.is
wget --no-check-certificate https://getpocket.com
wget --no-check-certificate https://statefarm.com
wget --no-check-certificate https://partypoker.com
wget --no-check-certificate https://rakuten.com
wget --no-check-certificate https://cbssports.com
wget --no-check-certificate https://makeuseof.com
wget --no-check-certificate https://kickstarter.com
wget --no-check-certificate https://nba.com
wget --no-check-certificate https://wideopencountry.com
wget --no-check-certificate https://staples.com
wget --no-check-certificate https://eventful.com
wget --no-check-certificate https://grubhub.com
wget --no-check-certificate https://ny.gov
wget --no-check-certificate https://pch.com
wget --no-check-certificate https://zmenu.com
wget --no-check-certificate https://orbitz.com
wget --no-check-certificate https://53.com
wget --no-check-certificate https://daily-stuff.com
wget --no-check-certificate https://va.gov
wget --no-check-certificate https://researchgate.net
wget --no-check-certificate https://whatsapp.com
wget --no-check-certificate https://silverscreenandroll.com
wget --no-check-certificate https://arstechnica.com
wget --no-check-certificate https://wordplays.com
wget --no-check-certificate https://alternativenation.net
wget --no-check-certificate https://americanexpress.com
wget --no-check-certificate https://sacbee.com
wget --no-check-certificate https://alibaba.com
wget --no-check-certificate https://emedicinehealth.com
wget --no-check-certificate https://instructables.com
wget --no-check-certificate https://gearpatrol.com
wget --no-check-certificate https://ebaumsworld.com
wget --no-check-certificate https://healthversed.com
wget --no-check-certificate https://windows.net

# bad ssl
wget --no-check-certificate https://expired.badssl.com
wget --no-check-certificate https://wrong.host.badssl.com
wget --no-check-certificate https://self-signed.badssl.com
wget --no-check-certificate https://untrusted-root.badssl.com
wget --no-check-certificate https://superfish.badssl.com
wget --no-check-certificate https://edellroot.badssl.com
wget --no-check-certificate https://dsdtestprovider.badssl.com
wget --no-check-certificate https://preact-cli.badssl.com
wget --no-check-certificate https://webpack-dev-server.badssl.com
wget --no-check-certificate https://sha1-intermediate.badssl.com
wget --no-check-certificate https://rc4.badssl.com
wget --no-check-certificate https://rc4-md5.badssl.com
wget --no-check-certificate https://dh480.badssl.com
wget --no-check-certificate https://dh512.badssl.com
wget --no-check-certificate https://dh1024.badssl.com
wget --no-check-certificate https://null.badssl.com
wget --no-check-certificate https://tls-v1-0.badssl.com
wget --no-check-certificate https://tls-v1-1.badssl.com
wget --no-check-certificate https://cbc.badssl.com
wget --no-check-certificate https://3des.badssl.com
wget --no-check-certificate https://revoked.badssl.com
wget --no-check-certificate https://pinning-test.badssl.com
wget --no-check-certificate https://invalid-expected-sct.badssl.com
wget --no-check-certificate https://10000-sans.badssl.com
wget --no-check-certificate https://sha384.badssl.com
wget --no-check-certificate https://sha512.badssl.com
wget --no-check-certificate https://rsa8192.badssl.com
wget --no-check-certificate https://no-subject.badssl.com
wget --no-check-certificate https://no-common-name.badssl.com
wget --no-check-certificate https://incomplete-chain.badssl.com
wget --no-check-certificate https://tls-v1-2.badssl.com
wget --no-check-certificate https://sha256.badssl.com
wget --no-check-certificate https://rsa2048.badssl.com
wget --no-check-certificate https://ecc256.badssl.com
wget --no-check-certificate https://ecc384.badssl.com
wget --no-check-certificate https://extended-validation.badssl.com
wget --no-check-certificate https://mozilla-modern.badssl.com

rm index.*
