#!/bin/bash

set -x

rm index.*
#sudo tshark -i en7 -a duration:60 -w ../data/cap01.pcap &
#sudo tshark -i en7 -a duration:60 -w cap01.pcap


for run in {1..10}
do
	# bad ssl
	wget --no-check-certificate https://expired.badssl.com
	wget --no-check-certificate https://wrong.host.badssl.com
	wget --no-check-certificate https://self-signed.badssl.com
	wget --no-check-certificate https://untrusted-root.badssl.com
	wget --no-check-certificate https://superfish.badssl.com
	wget --no-check-certificate https://edellroot.badssl.com
	wget --no-check-certificate https://dsdtestprovider.badssl.com
	wget --no-check-certificate https://preact-cli.badssl.com
	wget --no-check-certificate https://webpack-dev-server.badssl.com
	wget --no-check-certificate https://sha1-intermediate.badssl.com
	wget --no-check-certificate https://rc4.badssl.com
	wget --no-check-certificate https://rc4-md5.badssl.com
	wget --no-check-certificate https://dh480.badssl.com
	wget --no-check-certificate https://dh512.badssl.com
	wget --no-check-certificate https://dh1024.badssl.com
	wget --no-check-certificate https://null.badssl.com
	wget --no-check-certificate https://tls-v1-0.badssl.com
	wget --no-check-certificate https://tls-v1-1.badssl.com
	wget --no-check-certificate https://cbc.badssl.com
	wget --no-check-certificate https://3des.badssl.com
	wget --no-check-certificate https://revoked.badssl.com
	wget --no-check-certificate https://pinning-test.badssl.com
	wget --no-check-certificate https://invalid-expected-sct.badssl.com
	wget --no-check-certificate https://1000-sans.badssl.com
	wget --no-check-certificate https://10000-sans.badssl.com
	wget --no-check-certificate https://sha384.badssl.com
	wget --no-check-certificate https://sha512.badssl.com
	wget --no-check-certificate https://rsa8192.badssl.com
	wget --no-check-certificate https://no-subject.badssl.com
	wget --no-check-certificate https://no-common-name.badssl.com
	wget --no-check-certificate https://incomplete-chain.badssl.com
	wget --no-check-certificate https://tls-v1-2.badssl.com
	wget --no-check-certificate https://sha256.badssl.com
	wget --no-check-certificate https://rsa2048.badssl.com
	wget --no-check-certificate https://ecc256.badssl.com
	wget --no-check-certificate https://ecc384.badssl.com
	wget --no-check-certificate https://extended-validation.badssl.com
	wget --no-check-certificate https://mozilla-modern.badssl.com

	wget --no-check-certificate https://www.blogger.com
	wget --no-check-certificate https://apple.com
	wget --no-check-certificate https://www.google.com
	wget --no-check-certificate https://play.google.com
	wget --no-check-certificate https://adobe.com
	wget --no-check-certificate https://youtube.com
	wget --no-check-certificate https://plus.google.com
	wget --no-check-certificate https://microsoft.com
	wget --no-check-certificate https://docs.google.com
	wget --no-check-certificate https://support.google.com
	wget --no-check-certificate https://accounts.google.com
	wget --no-check-certificate https://en.wikipedia.org
	wget --no-check-certificate https://mozilla.org
	wget --no-check-certificate https://sites.google.com
	wget --no-check-certificate https://wordpress.org
	wget --no-check-certificate https://youtu.be
	wget --no-check-certificate https://linkedin.com
	wget --no-check-certificate https://creativecommons.org
	wget --no-check-certificate https://github.com
	wget --no-check-certificate https://maps.google.com
	wget --no-check-certificate https://drive.google.com
	wget --no-check-certificate https://vimeo.com
	wget --no-check-certificate https://googleusercontent.com
	wget --no-check-certificate https://istockphoto.com
	wget --no-check-certificate https://amazon.com
	wget --no-check-certificate https://vk.com
	wget --no-check-certificate https://medium.com
	wget --no-check-certificate https://www.yahoo.com
	wget --no-check-certificate https://bp.blogspot.com
	wget --no-check-certificate https://dailymotion.com
	wget --no-check-certificate https://live.com
	wget --no-check-certificate https://news.google.com
	wget --no-check-certificate https://bbc.co.uk
	wget --no-check-certificate https://scribd.com
	wget --no-check-certificate https://facebook.com
	wget --no-check-certificate https://reuters.com
	wget --no-check-certificate https://usatoday.com
	wget --no-check-certificate https://myspace.com
	wget --no-check-certificate https://mail.ru
	wget --no-check-certificate https://google.com.br
	wget --no-check-certificate https://feedburner.com
	wget --no-check-certificate https://opera.com
	wget --no-check-certificate https://amazon.co.jp
	wget --no-check-certificate https://google.co.jp
	wget --no-check-certificate https://cnn.com
	wget --no-check-certificate https://bbc.com
	wget --no-check-certificate https://google.es
	wget --no-check-certificate https://news.yahoo.com
	wget --no-check-certificate https://whatsapp.com
	wget --no-check-certificate https://pt.wikipedia.org
	wget --no-check-certificate https://fr.wikipedia.org
	wget --no-check-certificate https://uol.com.br
	wget --no-check-certificate https://wikimedia.org
	wget --no-check-certificate https://msn.com
	wget --no-check-certificate https://google.co.uk
	wget --no-check-certificate https://mediafire.com
	wget --no-check-certificate https://mail.google.com
	wget --no-check-certificate https://cloudflare.com
	wget --no-check-certificate https://paypal.com
	wget --no-check-certificate https://w3.org
	wget --no-check-certificate https://hugedomains.com
	wget --no-check-certificate https://line.me
	wget --no-check-certificate https://europa.eu
	wget --no-check-certificate https://developers.google.com
	wget --no-check-certificate https://slideshare.net
	wget --no-check-certificate https://es.wikipedia.org
	wget --no-check-certificate https://forbes.com
	wget --no-check-certificate https://theguardian.com
	wget --no-check-certificate https://nih.gov
	wget --no-check-certificate https://google.de
	wget --no-check-certificate https://dropbox.com
	wget --no-check-certificate https://gstatic.com
	wget --no-check-certificate https://imdb.com
	wget --no-check-certificate https://amazon.de
	wget --no-check-certificate https://nytimes.com
	wget --no-check-certificate https://cnet.com
	wget --no-check-certificate https://photos.google.com
	wget --no-check-certificate https://nasa.gov
	wget --no-check-certificate https://apache.org
	wget --no-check-certificate https://draft.blogger.com
	wget --no-check-certificate https://aliexpress.com
	wget --no-check-certificate https://ok.ru
	wget --no-check-certificate https://tinyurl.com
	wget --no-check-certificate https://picasaweb.google.com
	wget --no-check-certificate https://google.ru
	wget --no-check-certificate https://foxnews.com
	wget --no-check-certificate https://policies.google.com
	wget --no-check-certificate https://aol.com
	wget --no-check-certificate https://rakuten.co.jp
	wget --no-check-certificate https://addthis.com
	wget --no-check-certificate https://bloomberg.com
	wget --no-check-certificate https://engadget.com
	wget --no-check-certificate https://fb.com
	wget --no-check-certificate https://tools.google.com
	wget --no-check-certificate https://buydomains.com
	wget --no-check-certificate https://amazon.co.uk
	wget --no-check-certificate https://oracle.com
	wget --no-check-certificate https://wikia.com
	wget --no-check-certificate https://bing.com
	wget --no-check-certificate https://google.fr
	wget --no-check-certificate https://change.org
	wget --no-check-certificate https://wired.com
	wget --no-check-certificate https://abril.com.br
	wget --no-check-certificate https://issuu.com
	wget --no-check-certificate https://terra.com.br
	wget --no-check-certificate https://books.google.com
	wget --no-check-certificate https://steampowered.com
	wget --no-check-certificate https://youronlinechoices.com
	wget --no-check-certificate https://myaccount.google.com
	wget --no-check-certificate https://cbsnews.com
	wget --no-check-certificate https://www.wix.com
	wget --no-check-certificate https://privacyshield.gov
	wget --no-check-certificate https://mega.nz
	wget --no-check-certificate https://networkadvertising.org
	wget --no-check-certificate https://de.wikipedia.org
	wget --no-check-certificate https://yelp.com
	wget --no-check-certificate https://amazon.fr
	wget --no-check-certificate https://goo.gl
	wget --no-check-certificate https://cpanel.net
	wget --no-check-certificate https://lefigaro.fr
	wget --no-check-certificate https://ipv4.google.com
	wget --no-check-certificate https://groups.google.com
	wget --no-check-certificate https://yandex.ru
	wget --no-check-certificate https://harvard.edu
	wget --no-check-certificate https://translate.google.com
	wget --no-check-certificate https://undeveloped.com
	wget --no-check-certificate https://globo.com
	wget --no-check-certificate https://booking.com
	wget --no-check-certificate https://samsung.com
	wget --no-check-certificate https://code.google.com
	wget --no-check-certificate https://elmundo.es
	wget --no-check-certificate https://www.cdc.gov
	#wget --no-check-certificate https://un.org
	wget --no-check-certificate https://playstation.com
	wget --no-check-certificate https://goodreads.com
	wget --no-check-certificate https://wsj.com
	wget --no-check-certificate https://php.net
	wget --no-check-certificate https://disqus.com
	wget --no-check-certificate https://archive.org
	wget --no-check-certificate https://ted.com
	wget --no-check-certificate https://www.gov.uk
	wget --no-check-certificate https://files.wordpress.com
	wget --no-check-certificate https://washingtonpost.com
	wget --no-check-certificate https://google.it
	wget --no-check-certificate https://t.me
	wget --no-check-certificate https://elpais.com
	wget --no-check-certificate https://techcrunch.com
	wget --no-check-certificate https://rt.com
	wget --no-check-certificate https://telegram.me
	wget --no-check-certificate https://thesun.co.uk
	wget --no-check-certificate https://huffingtonpost.com
	wget --no-check-certificate https://ebay.com
	wget --no-check-certificate https://godaddy.com
	wget --no-check-certificate https://soundcloud.com
	wget --no-check-certificate https://ft.com
	wget --no-check-certificate https://android.com
	wget --no-check-certificate https://pinterest.com
	wget --no-check-certificate https://telegraph.co.uk
	wget --no-check-certificate https://hatena.ne.jp
	wget --no-check-certificate https://dailymail.co.uk
	wget --no-check-certificate https://hp.com
	wget --no-check-certificate https://secureserver.net
	wget --no-check-certificate https://sendspace.com
	#wget --no-check-certificate https://photos1.blogger.com
	#wget --no-check-certificate https://asus.com
	#wget --no-check-certificate https://ietf.org
	wget --no-check-certificate https://amazon.es
	wget --no-check-certificate https://www.livejournal.com
	wget --no-check-certificate https://so-net.ne.jp
	wget --no-check-certificate https://gooyaabitemplates.com
	wget --no-check-certificate https://abc.es
	wget --no-check-certificate https://ytimg.com
	wget --no-check-certificate https://bp0.blogger.com
	wget --no-check-certificate https://google.ca
	wget --no-check-certificate https://cpanel.com
	wget --no-check-certificate https://gofundme.com
	wget --no-check-certificate https://mozilla.com
	wget --no-check-certificate https://cornell.edu
	wget --no-check-certificate https://goo.ne.jp
	wget --no-check-certificate https://blackberry.com
	wget --no-check-certificate https://cnbc.com
	wget --no-check-certificate https://google.pl
	wget --no-check-certificate https://nature.com
	wget --no-check-certificate https://stores.jp
	wget --no-check-certificate https://sciencemag.org
	wget --no-check-certificate https://storage.canalblog.com
	wget --no-check-certificate https://get.google.com
	wget --no-check-certificate https://bitly.com
	wget --no-check-certificate https://viglink.com
	wget --no-check-certificate https://instagram.com
	wget --no-check-certificate https://stackoverflow.com
	wget --no-check-certificate https://wp.com
	wget --no-check-certificate https://rottentomatoes.com
	wget --no-check-certificate https://depositfiles.com
	wget --no-check-certificate https://yadi.sk
	wget --no-check-certificate https://fandom.com
	wget --no-check-certificate https://espn.com
	wget --no-check-certificate https://www.over-blog.com
	wget --no-check-certificate https://allaboutcookies.org
	wget --no-check-certificate https://bandcamp.com
	#wget --no-check-certificate https://cambridge.org
	wget --no-check-certificate https://doubleclick.net
	#wget --no-check-certificate https://rtve.es
	wget --no-check-certificate https://gravatar.com
	wget --no-check-certificate https://walmart.com
	wget --no-check-certificate https://ign.com
	wget --no-check-certificate https://abc.net.au
	wget --no-check-certificate https://marketingplatform.google.com
	wget --no-check-certificate https://mirror.co.uk
	wget --no-check-certificate https://ea.com
	wget --no-check-certificate https://lemonde.fr
	#wget --no-check-certificate https://clickbank.net
	#wget --no-check-certificate https://ikea.com
	#wget --no-check-certificate https://qq.com
	wget --no-check-certificate https://nhk.or.jp
	wget --no-check-certificate https://lycos.com
	wget --no-check-certificate https://nypost.com
	wget --no-check-certificate https://plesk.com
	wget --no-check-certificate https://bt.com
	wget --no-check-certificate https://ox.ac.uk
	wget --no-check-certificate https://ru.wikipedia.org
	wget --no-check-certificate https://imageshack.us
	wget --no-check-certificate https://naver.com
	wget --no-check-certificate https://foursquare.com
	wget --no-check-certificate https://buzzfeed.com
	wget --no-check-certificate https://marriott.com
	wget --no-check-certificate https://express.co.uk
	wget --no-check-certificate https://ja.wikipedia.org
	wget --no-check-certificate https://mysql.com
	wget --no-check-certificate https://weibo.com
	#wget --no-check-certificate https://repubblica.it
	wget --no-check-certificate https://list-manage.com
	wget --no-check-certificate https://gmail.com
	wget --no-check-certificate https://gizmodo.com
	wget --no-check-certificate https://photobucket.com
	wget --no-check-certificate https://theverge.com
	wget --no-check-certificate https://britannica.com
	wget --no-check-certificate https://about.com
	wget --no-check-certificate https://loc.gov
	wget --no-check-certificate https://thetimes.co.uk
	wget --no-check-certificate https://quora.com
	wget --no-check-certificate https://bp3.blogger.com
	wget --no-check-certificate https://yahoo.co.jp
	wget --no-check-certificate https://shopify.com
	wget --no-check-certificate https://netflix.com
	wget --no-check-certificate https://cisco.com
	wget --no-check-certificate https://id.wikipedia.org
	wget --no-check-certificate https://bp2.blogger.com
	wget --no-check-certificate https://google.co.in
	wget --no-check-certificate https://themeforest.net
	wget --no-check-certificate https://picasa.google.com
	wget --no-check-certificate https://naver.jp
	wget --no-check-certificate https://channel4.com
	wget --no-check-certificate https://npr.org
	#wget --no-check-certificate https://xinhuanet.com
	wget --no-check-certificate https://search.yahoo.com
	wget --no-check-certificate https://kickstarter.com
	wget --no-check-certificate https://ask.fm
	wget --no-check-certificate https://mashable.com
	#wget --no-check-certificate https://worldbank.org
	wget --no-check-certificate https://windowsphone.com
	wget --no-check-certificate https://finance.yahoo.com
	wget --no-check-certificate https://search.google.com
	wget --no-check-certificate https://alibaba.com
	wget --no-check-certificate https://shutterstock.com
	wget --no-check-certificate https://bund.de
	wget --no-check-certificate https://addtoany.com
	wget --no-check-certificate https://whitehouse.gov
	wget --no-check-certificate https://akamaihd.net
	wget --no-check-certificate https://office.com
	wget --no-check-certificate https://googleblog.com
	wget --no-check-certificate https://gnu.org
	wget --no-check-certificate https://000webhost.com
	wget --no-check-certificate https://ucoz.ru
	wget --no-check-certificate https://independent.co.uk
	wget --no-check-certificate https://sciencedaily.com
	wget --no-check-certificate https://ria.ru
	#wget --no-check-certificate https://unesco.org
	wget --no-check-certificate https://guardian.co.uk
	wget --no-check-certificate https://www.wikipedia.org
	wget --no-check-certificate https://columbia.edu
	wget --no-check-certificate https://dw.com
	#wget --no-check-certificate https://ig.com.br
	wget --no-check-certificate https://ovh.co.uk
	wget --no-check-certificate https://ovh.com
	wget --no-check-certificate https://parallels.com
	wget --no-check-certificate https://businessinsider.com
	wget --no-check-certificate https://pl.wikipedia.org
	wget --no-check-certificate https://google.nl
	wget --no-check-certificate https://a8.net
	wget --no-check-certificate https://mit.edu
	wget --no-check-certificate https://t.co
	wget --no-check-certificate https://nokia.com
	wget --no-check-certificate https://4shared.com
	wget --no-check-certificate https://skype.com
	wget --no-check-certificate https://nginx.org
	wget --no-check-certificate https://webmd.com
	wget --no-check-certificate https://vkontakte.ru
	wget --no-check-certificate https://sedo.com
	wget --no-check-certificate https://rapidshare.com
	wget --no-check-certificate https://dell.com
	wget --no-check-certificate https://welt.de
	wget --no-check-certificate https://xbox.com
	wget --no-check-certificate https://pixabay.com
	wget --no-check-certificate https://ggpht.com
	wget --no-check-certificate https://intel.com
	wget --no-check-certificate https://sciencedirect.com
	wget --no-check-certificate https://my.yahoo.com
	wget --no-check-certificate https://disney.com
	wget --no-check-certificate https://eventbrite.com
	wget --no-check-certificate https://instructables.com
	wget --no-check-certificate https://wikihow.com
	wget --no-check-certificate https://sky.com
	wget --no-check-certificate https://psychologytoday.com
	wget --no-check-certificate https://adssettings.google.com
	wget --no-check-certificate https://stanford.edu
	wget --no-check-certificate https://rambler.ru
	wget --no-check-certificate https://wpfr.net
	wget --no-check-certificate https://twitter.com
	wget --no-check-certificate https://huffpost.com
	wget --no-check-certificate https://twitch.tv
	wget --no-check-certificate https://bit.ly
	wget --no-check-certificate https://hm.com
	wget --no-check-certificate https://time.com
	wget --no-check-certificate https://nydailynews.com
	wget --no-check-certificate https://www.weebly.com
	wget --no-check-certificate https://spotify.com
	wget --no-check-certificate https://latimes.com
	wget --no-check-certificate https://cbc.ca
	wget --no-check-certificate https://ndtv.com
	wget --no-check-certificate https://about.me
	wget --no-check-certificate https://urbandictionary.com
	wget --no-check-certificate https://netvibes.com
	wget --no-check-certificate https://box.com
	wget --no-check-certificate https://berkeley.edu
	wget --no-check-certificate https://aboutads.info
	wget --no-check-certificate https://who.int
	wget --no-check-certificate https://smh.com.au
	wget --no-check-certificate https://princeton.edu
	wget --no-check-certificate https://academia.edu
	wget --no-check-certificate https://e-recht24.de
	wget --no-check-certificate https://economist.com
	wget --no-check-certificate https://iubenda.com
	wget --no-check-certificate https://indiatimes.com
	wget --no-check-certificate https://surveymonkey.com
	wget --no-check-certificate https://ovh.net
	wget --no-check-certificate https://newsweek.com
	wget --no-check-certificate https://entrepreneur.com
	wget --no-check-certificate https://abcnews.go.com
	wget --no-check-certificate https://wiley.com
	wget --no-check-certificate https://sapo.pt
	wget --no-check-certificate https://ibm.com
	wget --no-check-certificate https://it.wikipedia.org
	wget --no-check-certificate https://tripadvisor.com
	wget --no-check-certificate https://umich.edu
	wget --no-check-certificate https://vice.com
	wget --no-check-certificate https://spiegel.de
	wget --no-check-certificate https://thedailybeast.com
	wget --no-check-certificate https://newyorker.com
	wget --no-check-certificate https://mail.yahoo.com
	wget --no-check-certificate https://xing.com
	wget --no-check-certificate https://zdnet.com
	wget --no-check-certificate https://eonline.com
	wget --no-check-certificate https://wiktionary.org
	wget --no-check-certificate https://wbs-law.de
	wget --no-check-certificate https://archives.gov
	wget --no-check-certificate https://dribbble.com
	wget --no-check-certificate https://tabelog.com
	wget --no-check-certificate https://standard.co.uk
	wget --no-check-certificate https://chicagotribune.com
	wget --no-check-certificate https://fda.gov
	wget --no-check-certificate https://fastcompany.com
	wget --no-check-certificate https://disney.go.com
	wget --no-check-certificate https://bloglovin.com
	wget --no-check-certificate https://answers.yahoo.com
	wget --no-check-certificate https://csmonitor.com
	wget --no-check-certificate https://pastebin.com
	wget --no-check-certificate https://nationalgeographic.com
	wget --no-check-certificate https://example.com
	wget --no-check-certificate https://arstechnica.com
	wget --no-check-certificate https://teamviewer.com
	wget --no-check-certificate https://ebay.de
	wget --no-check-certificate https://geocities.jp
	wget --no-check-certificate https://nginx.com
	wget --no-check-certificate https://thenextweb.com
	wget --no-check-certificate https://cbslocal.com
	wget --no-check-certificate https://steamcommunity.com
	wget --no-check-certificate https://history.com
	wget --no-check-certificate https://adweek.com
	wget --no-check-certificate https://debian.org
	wget --no-check-certificate https://behance.net
	wget --no-check-certificate https://thefreedictionary.com
	wget --no-check-certificate https://state.gov
	wget --no-check-certificate https://offset.com
	wget --no-check-certificate https://imgur.com
	wget --no-check-certificate https://venturebeat.com
	wget --no-check-certificate https://chinadaily.com.cn
	wget --no-check-certificate https://washington.edu
	wget --no-check-certificate https://ustream.tv
	wget --no-check-certificate https://groups.yahoo.com
	wget --no-check-certificate https://foodnetwork.com
	wget --no-check-certificate https://calendar.google.com
	wget --no-check-certificate https://zendesk.com
	wget --no-check-certificate https://target.com
	wget --no-check-certificate https://ca.gov
	wget --no-check-certificate https://sfgate.com
	wget --no-check-certificate https://utexas.edu
	wget --no-check-certificate https://scientificamerican.com
	wget --no-check-certificate https://house.gov
	wget --no-check-certificate https://ebay.co.uk
	wget --no-check-certificate https://sina.com.cn
	wget --no-check-certificate https://icann.org
	wget --no-check-certificate https://liveinternet.ru
	wget --no-check-certificate https://plos.org
	wget --no-check-certificate https://allrecipes.com
	wget --no-check-certificate https://marketwatch.com
	wget --no-check-certificate https://cam.ac.uk
	wget --no-check-certificate https://scoop.it
	wget --no-check-certificate https://dictionary.com
	wget --no-check-certificate https://wattpad.com
	wget --no-check-certificate https://lifehacker.com
	wget --no-check-certificate https://calameo.com
	wget --no-check-certificate https://postimg.org
	wget --no-check-certificate https://etsy.com
	wget --no-check-certificate https://cmu.edu
	wget --no-check-certificate https://espn.go.com
	wget --no-check-certificate https://sputniknews.com
	wget --no-check-certificate https://billboard.com
	wget --no-check-certificate https://kinja.com
	wget --no-check-certificate https://thestar.com
	wget --no-check-certificate https://pcmag.com
	wget --no-check-certificate https://discovery.com
	wget --no-check-certificate https://slate.com
	wget --no-check-certificate https://e-monsite.com
	#wget --no-check-certificate https://nova.cz
	wget --no-check-certificate https://variety.com
	wget --no-check-certificate https://thoughtco.com
	wget --no-check-certificate https://bp1.blogger.com
	wget --no-check-certificate https://feedproxy.google.com
	wget --no-check-certificate https://usa.gov
	wget --no-check-certificate https://theatlantic.com
	wget --no-check-certificate https://pixnet.net
	#wget --no-check-certificate https://dreniq.com
	wget --no-check-certificate https://siemens.com
	wget --no-check-certificate https://sports.yahoo.com
	wget --no-check-certificate https://dropboxusercontent.com
	wget --no-check-certificate https://usnews.com
	wget --no-check-certificate https://daum.net
	wget --no-check-certificate https://narod.ru
	wget --no-check-certificate https://yale.edu
	wget --no-check-certificate https://people.com.cn
	wget --no-check-certificate https://www.nhs.uk
	wget --no-check-certificate https://mixcloud.com
	wget --no-check-certificate https://prestashop.com
	wget --no-check-certificate https://mercurynews.com
	wget --no-check-certificate https://fortune.com
	wget --no-check-certificate https://megaupload.com
	wget --no-check-certificate https://detik.com
	wget --no-check-certificate https://storify.com
	wget --no-check-certificate https://soratemplates.com
	wget --no-check-certificate https://ameblo.jp
	wget --no-check-certificate https://nicovideo.jp
	wget --no-check-certificate https://news.com.au
	wget --no-check-certificate https://softonic.com
	wget --no-check-certificate https://gen.xyz
	wget --no-check-certificate https://ap.org
	wget --no-check-certificate https://t-online.de
	wget --no-check-certificate https://www.canalblog.com

	wget --no-check-certificate https://newscientist.com
	wget --no-check-certificate https://biblegateway.com
	wget --no-check-certificate https://ftc.gov
	wget --no-check-certificate https://trustpilot.com
	wget --no-check-certificate https://biglobe.ne.jp
	wget --no-check-certificate https://hollywoodreporter.com
	wget --no-check-certificate https://google.com.au
	wget --no-check-certificate https://nifty.com
	wget --no-check-certificate https://digg.com
	wget --no-check-certificate https://usgs.gov
	wget --no-check-certificate https://boston.com
	wget --no-check-certificate https://nba.com
	wget --no-check-certificate https://connect.over-blog.com
	wget --no-check-certificate https://mayoclinic.org
	wget --no-check-certificate https://m.wikipedia.org
	wget --no-check-certificate https://springer.com
	wget --no-check-certificate https://nikkei.com
	wget --no-check-certificate https://amazon.ca
	wget --no-check-certificate https://weather.com
	wget --no-check-certificate https://vox.com
	wget --no-check-certificate https://video.google.com
	wget --no-check-certificate https://researchgate.net
	wget --no-check-certificate https://cnil.fr
	wget --no-check-certificate https://axs.com
	wget --no-check-certificate https://merriam-webster.com
	wget --no-check-certificate https://prezi.com
	wget --no-check-certificate https://web.fc2.com
	wget --no-check-certificate https://fifa.com
	wget --no-check-certificate https://stuff.co.nz
	wget --no-check-certificate https://netsons.com
	wget --no-check-certificate https://metro.co.uk
done


rm index.*
